### ISSUE TITLE
api/blocks/txs/ Interface error

### ISSUE THREAD

**Issue by 90hacker** [input-output-hk/cardano-rest#105]
| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | cardano-explorer-api:3.0.0 |
| Platform     | Docker          |
| Installation | From Github Release           |

# Steps to Reproduce
I am using
Get brief information about transactions.

curl localhost:18100/api/blocks/txs/13e7cc6b2e4cc922ca151d3f5d6455082d8b5633c1505d2be328973005b43b07
The information it gave me(Something went wrongroot)

cardanorest_cardano-explorer-api log info 
```
OnClauseWithoutMatchingJoinException "\"tx2\".\"id\" = \"tx_in\".\"tx_out_id\""
```

## Expected behavior

Return correct transaction information

**Comment by KtorZ** [comment]
Hi, I cannot reproduce this on Mainnet. What networks are you on?
