### ISSUE TITLE
Submit-api does not start with docker, does not have any logs

### ISSUE THREAD

**Issue by xdzurman** [input-output-hk/cardano-rest#108]
I updated my node to 1.24.2, db sync to 7.1.0. Worked fine with cardano submit api 2.1.3, even successful transactions sent. Then I updated submit api to 3.1.0, it has no docker logs though, and does not work.

3.0.0 runs fine

**Comment by xdzurman** [comment]
@KtorZ

**Comment by KtorZ** [comment]
@xdzurman You have closed the issue? What happened?

**Comment by xdzurman** [comment]
The submit api started fine, but due to #109 , submitting healthcheck transactions silently failed. And since no logs about the service being actually started were streamed, I thought it was dead from the start.
