### ISSUE TITLE
submit api service does not log the full tx id

### ISSUE THREAD

**Issue by ArturWieczorek** [input-output-hk/cardano-rest#11]
# Context
 
 

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | commit 86bc08f5491a45376b46d4c068d1740b0919f8ee on master |
| Platform     | Linux          |
| Installation |             |

# Steps to Reproduce

1. Create a valid transaction file and submit it to `submit-api` 

- On the client side you will see a 202 response with full transaction id:

`cardano-rest/submit-api$ curl -X POST --header "Content-Type:application/cbor" --data-binary @../../cardano-node/genesis-tx.bin http://localhost:8101/api/submit/tx
`
> "1239e0d0186966cbb2ca0ad08d97e0cea38d12799e011b8135dfc69530b767e2"

- On the submit api side you will get the shortened id of transaction logged:

> cardano-rest/submit-api$ /home/artur/Projects/DB_Sync/cardano-rest/dist-newstyle/build/x86_64-linux/ghc-8.6.5/cardano-submit-api-2.0.0/x/cardano-submit-api/build/cardano-submit-api/cardano-submit-api --config config/local-config.yaml --genesis-file ../../cardano-node/configuration/genesis/genesis.json --socket-path ../../cardano-node/socket/0 --port 8101
> [cardano-tx-submit:Info:9] [2020-03-19 14:40:21.29 UTC] Running tx-submit node
> [cardano-tx-submit:Info:9] [2020-03-19 14:40:21.29 UTC] NetworkMagic: RequiresMagic 459045235
> [cardano-tx-submit:Info:9] [2020-03-19 14:40:21.29 UTC] localInitiatorNetworkApplication: connecting to node via "../../cardano-node/socket/0"
> [cardano-tx-submit:Info:10] [2020-03-19 14:40:21.29 UTC] Running tx-submit web server on http://localhost:8101/
> [cardano-tx-submit:Info:23] [2020-03-19 14:42:36.18 UTC] txSubmitPost: received 249 bytes
> [cardano-tx-submit:Info:23] [2020-03-19 14:42:36.18 UTC] txSubmitPost: 1239e0d0186966cb

## Expected behavior

`submit api` should return the full tx id just like client

## Actual behavior
 
`submit api` returns the shortened tx id

---

# Resolution 

---

# QA

**Comment by kevinhammond** [comment]
I can't seem to edit this.  Could you add labels byron and priority high, please @ArturWieczorek - then we will pick them up for action.

**Comment by KtorZ** [comment]
@ArturWieczorek , reading your issue / comment after stepping back a bit. Is the issue actually that the **log output** on the cardano-submit-api service is truncated? However, the transaction id returned by the service as a response to the JSON is actually okay? 
 
If that is the case, then this is a non-issue and we can close this ticket right away :blush:

**Comment by erikd** [comment]
I agree that not logging the full tx id is not a huge issue, but if we did want to full tx id logged, the fix is a trivial one liner.

**Comment by KtorZ** [comment]
A truncated log line is totally fine. I'd just like confirmation from Arthur about this before closing the ticket :pray: ?

**Comment by erikd** [comment]
Its not even truncated, the official `Builder` formatter prints a shortened version of the hash. If you want the full hash, you just change formatters.

**Comment by KtorZ** [comment]
What's the difference between "a shortened version of the hash" and a truncated hash :) ?

**Comment by erikd** [comment]
The shortened version is whatever the default `Builder` for `TxId` is, and that shortens the hash (which from memory removes chars from the middle). There is also a full builder.

**Comment by erikd** [comment]
Current one is probably `Cardano.Crypto.Hashing.mediumHashF` and the full on is (I think) `hashHexF`.

**Comment by ArturWieczorek** [comment]
@KtorZ 

> Is the issue actually that the log output on the cardano-submit-api service is truncated? However, the transaction id returned by the service as a response is actually okay?
> 
> If that is the case, then this is a non-issue and we can close this ticket right away

Yes, the transaction id returned by the service as a response to the client is OK and only the log output from the service is shortened.

**Comment by ArturWieczorek** [comment]
Closing this issue - let me know if I should open a separate enhancement ticket for printing full hash or this is not needed.

**Comment by KtorZ** [comment]
> or this is not needed.

:point_up:
