### ISSUE TITLE
Multi asset support

### ISSUE THREAD

**Issue by xdzurman** [input-output-hk/cardano-rest#124]
Hello.

Will submit-api be ready for Mary hard fork (sending multi asset txs)? You mention that cardano-rest will survive Mary hard fork, but does that mean that signed multi-asset txs will go through?

Thanks

**Comment by KtorZ** [comment]
>  @xdzurman Will submit-api be ready for Mary hard fork 
Yes.

>  (sending multi asset txs)? 
No. 

---

The submit-api from cardano-rest is now deprecated and, although this repository will survive the Mary hard-fork (as it survives the Allegra one), it will however **not include** any features introduced after Shelley. The submit-api would expect transactions in the Shelley format and will choke on any features that are Allegra or Mary-specific. 

We strongly suggest to switch to better alternatives with more support such as:

- https://github.com/input-output-hk/cardano-graphql
- https://github.com/input-output-hk/cardano-rosetta

Here's a migration guide to help transitioning: https://input-output-hk.github.io/cardano-rest/migration-guide/
