### ISSUE TITLE
cbeSlot fetched from node tip instead of being calculated

### ISSUE THREAD

**Issue by rdlrt** [input-output-hk/cardano-rest#19]
# Context
 
Trying with an alternate genesis with reduced EpochSlots (from 21600 to 2000). When querying cardano-rest (/api/blocks/pages), the cbeSlot does to respect the change - as the slot_no in DB does not reset after 2000 slots.

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | all|
| Platform     | all     |
| Installation | master   |

# Steps to Reproduce

Steps to reproduce the behavior.

1. Connect to a genesis whose k is set to low value (eg: 200).
2. Query /api/blocks/pages endpoint, and verify cbeEpoch and cbeSlot. You would see that while cbeEpoch reflects correctly, cbeSlot reports slot assuming that goes far beyon.

For example, when cardano-node is at epoch 8, slot 1932 , Rest shows cbeEpoch as 8 , cbeSlot as **_17932_** instead. It looks like the field slot_no

## Expected behavior

cbeSlot should reflect the correct slot number with respect to genesis configuration. In the above example, it would be 1932.

## Actual behavior
 
Shows invalid cbeSlot (in above example, it shows 17932 - which would be valid if EpochSlot was 21600 instead.

**Comment by rdlrt** [comment]
In the current state, my understanding is this would be automatically resolved with input-output-hk/cardano-db-sync#84, but left it here for any reports of issues against cardano-rest , and if my understanding is incorrect 😄

**Comment by disassembler** [comment]
resolved by #78
