### ISSUE TITLE
 Poor performance querying address API

### ISSUE THREAD

**Issue by neville-freeman** [input-output-hk/cardano-rest#28]
Two queries currently have poor performance when the address being querieD has a large number of transactions (10000 or more). Those queries are:

/api/block/{blkHash}/address/{address}
/api/addresses/summary/{address}

Tested as follows: I wrote a script (1) to call /api/blocks/pages against the Cardano Rest and Cardano SL machines at the same time. Here I saw roughly the same response times. 

I also wrote a second script (2) to query /api/addresses/summary/{address}. This is much slower on Rest than on cardano-sl. 

Also when I run watch -n 1 script_two and execute script 1 simultaneously, I see slower script 1 response from Rest. The more often I execute script two, the slower script one's response becomes. It seems to be related to https://github.com/input-output-hk/cardano-explorer/issues/186,

**Comment by rhyslbw** [comment]
https://github.com/input-output-hk/cardano-rest/issues/31#issuecomment-646491493
