### ISSUE TITLE
pagination over tx list API

### ISSUE THREAD

**Issue by roccomuso** [input-output-hk/cardano-rest#31]
Other than poor performance reported here: https://github.com/input-output-hk/cardano-rest/issues/28

is there a way to paginate over `/explorer/api/addresses/summary/<address>` API?
That's an heavy call if an address has more than 1000 tx.

**Comment by rhyslbw** [comment]
This API was brought forward as a backwards-compatible implementation developed in `cardano-sl`. For more control over the response, we suggest considering https://github.com/input-output-hk/cardano-graphql
