### ISSUE TITLE
are API returned txs confirmed?

### ISSUE THREAD

**Issue by roccomuso** [input-output-hk/cardano-rest#32]
Are txs returned by `/api/addresses/summary/<address>` confirmed?
How do I check if txs are still pending/waiting for a confirmation?
Any status field available? documentation says nothing about this.

**Comment by rhyslbw** [comment]
Yes, this API queries the `cardano-db-sync` managed database, which is following the chain.
 
> How do I check if txs are still pending/waiting for a confirmation?

The question was recently asked internally, response from @dcoutts:

> In principle it would be possible but this has not been a priority for us because things live in the mempool for such a short period of time (since we produce blocks frequently).
