### ISSUE TITLE
/api/submit/tx Connection timed out

### ISSUE THREAD

**Issue by atomlab** [input-output-hk/cardano-rest#40]
Hi. How debugging case when request to`/api/submit/tx` finished by error `Connection timed out`.

cardano-submit-api logs

```
[cardano-tx-submit:Info:10] [2020-07-10 13:58:09.41 UTC] Running tx-submit web server on http://localhost:8101/
[cardano-tx-submit:Info:9] [2020-07-10 13:58:09.41 UTC] Running tx-submit node
[cardano-tx-submit:Info:9] [2020-07-10 13:58:09.41 UTC] NetworkMagic: RequiresNoMagic 764824073
[cardano-tx-submit:Info:9] [2020-07-10 13:58:09.41 UTC] localInitiatorNetworkApplication: connecting to node via "/data/node.socket"
[cardano-tx-submit:Info:3809] [2020-07-11 00:17:52.81 UTC] txSubmitPost: received 320 bytes
[cardano-tx-submit:Info:3832] [2020-07-11 00:21:15.58 UTC] txSubmitPost: received 271 bytes
[cardano-tx-submit:Info:3853] [2020-07-11 00:24:30.40 UTC] txSubmitPost: received 320 bytes
[cardano-tx-submit:Info:4095] [2020-07-11 01:03:58.58 UTC] txSubmitPost: received 271 bytes
[cardano-tx-submit:Info:4110] [2020-07-11 01:06:22.77 UTC] txSubmitPost: received 271 bytes
[cardano-tx-submit:Info:4121] [2020-07-11 01:08:01.57 UTC] txSubmitPost: received 271 bytes
[cardano-tx-submit:Info:4222] [2020-07-11 01:24:21.14 UTC] txSubmitPost: received 271 bytes
[cardano-tx-submit:Info:4538] [2020-07-11 02:15:57.86 UTC] txSubmitPost: received 271 bytes
[cardano-tx-submit:Info:4542] [2020-07-11 02:16:20.79 UTC] txSubmitPost: received 271 bytes
[cardano-tx-submit:Info:4559] [2020-07-11 02:19:05.41 UTC] txSubmitPost: received 320 bytes
[cardano-tx-submit:Info:4623] [2020-07-11 02:29:20.07 UTC] txSubmitPost: received 271 bytes
[cardano-tx-submit:Info:5328] [2020-07-11 04:24:44.27 UTC] txSubmitPost: received 271 bytes
[cardano-tx-submit:Info:5873] [2020-07-11 05:53:48.77 UTC] txSubmitPost: received 633 bytes
[cardano-tx-submit:Info:5893] [2020-07-11 05:57:05.14 UTC] txSubmitPost: received 633 bytes
[cardano-tx-submit:Info:5927] [2020-07-11 06:02:20.06 UTC] txSubmitPost: received 633 bytes
```

I expect see 
```
[cardano-tx-submit:Info:75] [2020-07-11 09:45:55.03 UTC] txSubmitPost: received 271 bytes
[cardano-tx-submit:Info:75] [2020-07-11 09:45:55.06 UTC] txSubmitPost: 29e019d104fbb120
```

**Comment by yanpl** [comment]
When will this bug be fixed?

**Comment by yanpl** [comment]
Now I generate a signed transaction (testnet), but when I call /api/submit/tx, this end-point returns nothing, the server log only prints such a log
cardano-submit-api_1_92a9674910e3 | [cardano-tx-submit:Info:158] [2020-07-20 09:17:39.95 UTC] txSubmitPost: received 245 bytes
Now I’m not sure if there is a problem with my own signature transaction or the /api/submit/tx interface.

The docker image I used is as follows:

REPOSITORY                         TAG                 IMAGE ID            CREATED             SIZE
inputoutput/cardano-db-sync        latest              ebec529f733d        2 weeks ago         993MB
inputoutput/cardano-node           latest              8ebd414ae5df        2 weeks ago         777MB
inputoutput/cardano-explorer-api   2.0.0               49cf49c1ff05        3 months ago        573MB
inputoutput/cardano-submit-api     latest              466f586bad79        3 months ago        586MB
postgres                           11.5-alpine         da01ecfbabe1        9 months ago        71.8MB

The signed transaction hex of the testnet I generated is as follows：
82839f8200d818582482582004e908b5982fb2caa3a341c6d6bb73f3cf7c4e71fe691ebf5e85eda609e22a5600ff9f8282d818582883581c0e3faf23320c6a0d19bb52fbb95d2dd35b9b7078fa3a830e3a9d5173a102451a4170cb17001a6d8736d61a3b8b87c0ffa0818200d8185885825840c1a1347e302e4d6e54ed5dbdf6248eecb9518209b684553c2ae99e3cdf19d110000000000000000000000000000000000000000000000000000000000000000058403c6f3bc3d4317563b8751233ddd35fd3b6829a5ab01638618053af185ae41b3dc0dd8510fe205f1adbb56705cf84ff71e462e6a5978cd3ffb889c637c04ac301

base64:
goOfggDYGFgkglggBOkItZgvssqjo0HG1rtz8898TnH+aR6/XoXtpgniKlYA/5+CgtgYWCiDWBwOP68jMgxqDRm7Uvu5XS3TW5twePo6gw46nVFzoQJFGkFwyxcAGm2HNtYaO4uHwP+ggYIA2BhYhYJYQMGhNH4wLk1uVO1dvfYkjuy5UYIJtoRVPCrpnjzfGdEQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABYQDxvO8PUMXVjuHUSM93TX9O2gppasBY4YYBTrxha5Bs9wN2FEP4gXxrbtWcFz4T/ceRi5qWXjNP/uInGN8BKwwE=

Can anyone tell me that this self-signed transaction is correct?

**Comment by intricate** [comment]
@atomlab @yanpl: At the moment, I'm updating `cardano-submit-api` to use the new `cardano-api` which should _hopefully_ indirectly fix these issues that you're seeing. When I raise a PR for it, I'll post a comment linking to it.

**Comment by yanpl** [comment]
@intricate: Great, looking forward to it

**Comment by intricate** [comment]
@atomlab @yanpl: Would you mind trying this out now that https://github.com/input-output-hk/cardano-rest/pull/46 has been merged?

**Comment by yanpl** [comment]
@intricate ，I use the latest code and call /api/submit/tx end-point, but nothing is returned :(

**Comment by intricate** [comment]
Can you show me the output of `cardano-node --version`? Also, what network are you connecting to? i.e. mainnet? a local testnet?

**Comment by yanpl** [comment]
@intricate 
cardano-node --version output
```
bash-4.4# /nix/store/50agaxf819rplcr9619w662kkiif9hn4-cardano-node-exe-cardano-node-1.14.2/bin/cardano-node --version
cardano-node 1.14.2 - linux-x86_64 - ghc-8.6
git rev 924a6f7d8c2bdb1bf525be8b0d5626e440697b01
```

I am using a local testnet

Cardano related process information is as follows
```
root@adfa98899:~# ps -ef|grep cardano
root      9469  9018  0 10:14 pts/1    00:00:00 grep --color=auto cardano
root     10995 10977  0 Jul22 ?        00:03:10 /nix/store/50agaxf819rplcr9619w662kkiif9hn4-cardano-node-exe-cardano-node-1.14.2/bin/cardano-node run --config /nix/store/9xvk6ix8lhyxcq9nzcv9ghsviw3xvmif-config-0.json --database-path /data/db --topology /nix/store/dpajyi2vaychwps1x7d20c2ddls4kf62-topology.yaml --host-addr 127.0.0.1 --port 3001 --socket-path /ipc/node.socket
root     11114 11096  0 Jul22 ?        00:00:11 /nix/store/cgrpd3alszxhh44z2xcqlj8ijiwifzjf-cardano-submit-api-2.0.0-exe-cardano-submit-api/bin/cardano-submit-api --socket-path /data/node.socket --genesis-file /nix/store/7106qjwral616j6p5049m7hhi5ih0r33-testnet-genesis.json --port 8101 --config /nix/store/m5sdi0j8wsqblzya482y467bal5di1p3-submit-api.json
root     12392 12351  1 Jul22 ?        00:21:57 /nix/store/mizippfq1vagv6iiwkh4ly85a5p0h7cw-cardano-db-sync-exe-cardano-db-sync-2.1.0/bin/cardano-db-sync --config /nix/store/yg3015jyqi45z4ggl2xabm0lv3anjrlf-config.json --genesis-file /nix/store/7106qjwral616j6p5049m7hhi5ih0r33-testnet-genesis.json --socket-path /node-ipc/node.socket --schema-dir /nix/store/7rbfljczglgd45gjv06gg978mf1xgb8r-schema
root     12587 12563  0 Jul22 ?        00:00:00 /nix/store/1lrl741npvxdzgpk03i0pyqal4267k5y-cardano-explorer-api-2.0.0-exe-cardano-explorer-api/bin/cardano-explorer-api
70       12665 11981  0 Jul22 ?        00:00:00 postgres: cardano cexplorer 172.30.0.6(37164) idle
```

**Comment by intricate** [comment]
Ah okay, I see. I've been using more recent versions of `cardano-node` with `cardano-rest`. I'll see if I can reproduce this issue with that version of `cardano-node`.

**Comment by yanpl** [comment]
I can send the transaction successfully by using the following docker images configuration on the local testnet.

`CARDANO_NODE_VERSION=1.14.2 CARDANO_DB_SYNC_VERSION=2.1.0 CARDANO_EXPLORER_API_VERSION=2.0.0 CARDANO_SUBMIT_API_VERSION=f37c974a271294c85455fbe69ea32c8ccbfb5043 NETWORK=testnet docker-compose up`

The docker image `inputoutput/cardano-submit-api:latest` on the website of `hub.docker.com` will cause the transaction to fail

`docker image DIGEST:sha256:9cefe72c78012f237c125dc9a7c1c833911edee3b1b57f11d8468365d6d70ef1 and PUSHED by rhyslbw`

**Comment by intricate** [comment]
@yanpl: So when you said you were using the "latest code" in a previous comment, you meant the `latest` image from Docker? Looking at hub.docker.com, it appears that both the `latest` and `f37c974a271294c85455fbe69ea32c8ccbfb5043` images are from around 3 months ago. 

I should have been more clear, but I was suggesting that you should try building a much more recent revision of `cardano-rest` (such as the `master` branch). I'm also seeing that there's a `master` image on hub.docker.com that's very recent (from a couple hours ago). Maybe try that one.

**Comment by intricate** [comment]
@yanpl: Ah okay, so when you said you were using the "latest code" in a previous comment, you meant the `latest` image from Docker? Looking at hub.docker.com, it appears that both the `latest` and `f37c974a271294c85455fbe69ea32c8ccbfb5043` images are from around 3 months ago.

I should have been more clear, but you should test this out with a much more recent revision of `cardano-submit-api` (such as on the `master` branch). I'm also seeing that there's a `master` image on hub.docker.com that's very recent (from a couple hours ago). Could you try that image and let me know if it works?

I don't manage the Docker images, but I suppose we'll have to update the `latest` image in the near future.

**Comment by rhyslbw** [comment]
@intricate `latest` is a proxy for the most recent release

**Comment by atomlab** [comment]
Something has changed with startup options? This is build from master commit [1141b72](https://github.com/input-output-hk/cardano-rest/commit/1141b7226b39e9bd8ca1fb3ce9e7727a12af120c) 
```
podman run \
--pod cardano \
--mount type=bind,source=/opt/cardano/node-ipc,destination=/node-ipc \
-p 8101:8101 \
-e NETWORK=mainnet \
-e CARDANO_NODE_SOCKET_PATH=/node-ipc/node.socket \
hub:9080/cardano-submit-api:master-1141b72-5
```

output
```
Invalid option `--genesis-file'

Usage: cardano-submit-api --config FILEPATH
                          [--shelley-mode | --byron-mode [--epoch-slots NATURAL]
                            [--security-param NATURAL] |
                            --cardano-mode [--epoch-slots NATURAL]
                            [--security-param NATURAL]]
                          (--mainnet | --testnet-magic NATURAL)
                          --socket-path FILEPATH --port PORT
  Cardano transaction submission web API.
```

**Comment by intricate** [comment]
@atomlab: Yes the CLI options have changed. So you no longer need to specify a `--genesis-file`. 

Instead, you specify:

- the protocol mode: 
  - `--byron-mode` for communicating with a pure Byron node
  - `--shelley-mode` for communicating with a pure Shelley node
  - `--cardano-mode` for communicating with a node running the composite Byron and Shelley protocol (protocol which starts in Byron and transitions to Shelley)

- the network: `--mainnet` or `--testnet-magic`

**Comment by intricate** [comment]
@atomlab: Yes the CLI options have changed. So you no longer need to specify a `--genesis-file`. 

Instead, you specify:

- the protocol mode: 
  - `--byron-mode` for communicating with a node running in Byron-only mode
  - `--shelley-mode` for communicating with a node running in Shelley-only mode
  - `--cardano-mode` for communicating with a node running in the full Cardano mode (protocol which starts in Byron and transitions to Shelley)

- the network: `--mainnet` or `--testnet-magic`

**Comment by atomlab** [comment]
@intricate Thank you for response. But which parameters should be set for run docker container? 

I watch [docker-compose.yml](https://github.com/input-output-hk/cardano-rest/blob/master/docker-compose.yml) as instruction for service run.
Or which build args for build docker image should I set?

**Comment by intricate** [comment]
My apologies, I didn't update the relevant `docker` stuff for `master`. Will need to address this and get back to you.
