### ISSUE TITLE
/api/blocks/txs returns "No block found" if block has no transactions

### ISSUE THREAD

**Issue by quyse** [input-output-hk/cardano-rest#41]
# Context

`/api/blocks/txs` returns "No block found" if block exists, but has no transactions.

Cardano-SL had correct behavior.

# Steps to Reproduce

Using fresh docker image `inputoutput/cardano-explorer-api:master` (digest 973f4480ec77), on Cardano mainnet:

```
curl 'http://127.0.0.1:8100/api/blocks/txs/30830e8bd51959ddee37e5a3517d02d52d5f9b9c416edb7571a3e90e3a588599'
```

## Expected behavior

```
{"Right":[]}
```

## Actual behavior

```
{"Left":"No block found"}
```

**Comment by rhyslbw** [comment]
@quyse I suggest moving to https://github.com/input-output-hk/cardano-graphql for a properly maintained solution

**Comment by quyse** [comment]
@rhyslbw Thanks for the suggestion. It seems GraphQL is mostly intended for explorer-like applications, with ability to do filtering/aggregations and such, but also with arbitrary non-documented limitations such as this https://github.com/input-output-hk/cardano-graphql/issues/276 which makes it hard to use for extraction of raw blockchain data.

**Comment by rhyslbw** [comment]
@quyse
> It seems GraphQL is mostly intended for explorer-like applications, with ability to do filtering/aggregations and such

It's not the intent.

> makes it hard to use for extraction of raw blockchain data.
Can you detail what you're intending to do this data? Are you operating outside the volatile section of the chain?
