### ISSUE TITLE
Failed to connect to the cardano-rest explorer api

### ISSUE THREAD

**Issue by freddieee** [input-output-hk/cardano-rest#62]
# Context

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | 2.1.0 |
| Platform     | Docker         |
| Installation | From Github Release          |

# Steps to Reproduce

1. pull the latest release from github
2. rm `.example` of the files in the folder `config`
3. `NETWORK=mainnet docker-compose up -d --build && docker-compose logs -f`
4. After several hours of synching, run `curl http://localhost:8100/api/txs/last `
## Expected behavior
json response
## Actual behavior
`curl: (56) Recv failure: Connection reset by peer`

When I checked the log from the  explorer api
`docker-compose logs -f cardano-explorer-api`
the log shows

> `Attaching to cardano-rest_cardano-explorer-api_1
cardano-explorer-api_1  | Generating PGPASS file
cardano-explorer-api_1  | [Info] Connecting to database at postgres:5432
cardano-explorer-api_1  | cardano-explorer-api: libpq: failed (could not send data to server: No route to host
cardano-explorer-api_1  | could not send SSL negotiation packet: No route to host
cardano-explorer-api_1  | )

---

**Comment by rhyslbw** [comment]
Please try the [latest version](https://github.com/input-output-hk/cardano-rest/releases/tag/2.1.1) and reopen if still experiencing issues
