### ISSUE TITLE
Submit api environment variables

### ISSUE THREAD

**Issue by ksemaev** [input-output-hk/cardano-rest#66]
Guys,  new release https://github.com/input-output-hk/cardano-rest/releases/tag/2.1.0 had changed the default port for api, and by default api is now listening only from localhost.
Since we use docker/compose etc we're passing the config with vars, and I can't figure out var names to change port/host values, please advice.

BTW this port changed but stayed in compose: https://github.com/input-output-hk/cardano-rest/blob/master/docker-compose.yml#L89

**Comment by ksemaev** [comment]
And with current layout with number of different scripts with automatically created names like ` /nix/store/mqm19lhcckx2aabbw3xas75qvyrlrs8m-cardano-submit-api` and `/nix/store/p7bg0sxgddrfsr6946zg391zidg71hdq-entry-point/bin/entry-point` I can't really replace entrypoint as it'll change on next release/build

**Comment by rhyslbw** [comment]
Hi @ksemaev 
https://github.com/input-output-hk/cardano-rest/commit/71a09286d5f183721bf543fae6d74d209bfe0489 should address the issues here. See discussion and links in https://github.com/input-output-hk/cardano-rest/issues/72 to assist with config
