### ISSUE TITLE
[cardano-submit-api] Run docker containers with args

### ISSUE THREAD

**Issue by atomlab** [input-output-hk/cardano-rest#72]
Hi. Version 2.1.1
I run docker container with args
```
  "Args": [
         "--listen-address=*",
          "--port=8090"
```

But cardano-submit-api still listen on localhost
```
$ podman logs cardano-submit-api
[Info] Running server on 127.0.0.1:8090
```

This entrypoint don't respect args.  Only one condition accept command args `$@`. All another conditions don't respect command line args.

```
bash-4.4# cat /nix/store/p7bg0sxgddrfsr6946zg391zidg71hdq-entry-point/bin/entry-point
#!/nix/store/hrpvwkjz04s9i4nmli843hyw9z4pwhww-bash-4.4-p23/bin/bash
# set up /tmp (override with TMPDIR variable)
mkdir -p -m 1777 tmp
if [[ -z "$NETWORK" ]]; then
   exec /nix/store/l21m2bfgq1ykhcmgb3a5y90jrwgbpjjr-cardano-submit-api-exe-cardano-submit-api-2.1.0/bin/cardano-submit-api $@
   elif [[ "$NETWORK" == "mainnet" ]]; then
  exec /nix/store/mqm19lhcckx2aabbw3xas75qvyrlrs8m-cardano-submit-api

elif [[ "$NETWORK" == "mainnet_candidate" ]]; then
  tx submission not supported on mainnet_candidate
  exit 1

elif [[ "$NETWORK" == "mainnet_candidate_2" ]]; then
  tx submission not supported on mainnet_candidate_2
  exit 1

elif [[ "$NETWORK" == "mainnet_candidate_3" ]]; then
  tx submission not supported on mainnet_candidate_3
  exit 1

elif [[ "$NETWORK" == "selfnode" ]]; then
  tx submission not supported on selfnode
  exit 1

elif [[ "$NETWORK" == "shelley_qa" ]]; then
  tx submission not supported on shelley_qa
  exit 1

elif [[ "$NETWORK" == "shelley_selfnode" ]]; then
  tx submission not supported on shelley_selfnode
  exit 1

elif [[ "$NETWORK" == "shelley_staging" ]]; then
  exec /nix/store/zvdzys7fjq5kz22k72grr69cksmkhbhk-cardano-submit-api

elif [[ "$NETWORK" == "shelley_testnet" ]]; then
  tx submission not supported on shelley_testnet
  exit 1

elif [[ "$NETWORK" == "staging" ]]; then
  exec /nix/store/zzak6w1rhbpacv5z4kj8fkq2rq74bg9j-cardano-submit-api

elif [[ "$NETWORK" == "testnet" ]]; then
  exec /nix/store/rnajymmz84dimi5gyvbmv5pk2ckra7af-cardano-submit-api

   else
     echo "Managed configuration for network "$NETWORK" does not exist"
   fi
fi
```

**Comment by atomlab** [comment]
I think it can be fixed in 140 line of [docker.nix](https://github.com/input-output-hk/cardano-rest/blob/3f278f36dd6a2b8fa8287e10af401c57a6d5ab28/nix/docker.nix#L140)

**Comment by xdzurman** [comment]
https://github.com/input-output-hk/cardano-node/issues/1307

**Comment by atomlab** [comment]
> [input-output-hk/cardano-node#1307](https://github.com/input-output-hk/cardano-node/issues/1307)

thanks for reply. Are you going to implement args managing for `cardano-submit-api` as it works for cardano-node? Cardano-node [docker.nix](https://github.com/input-output-hk/cardano-node/blob/f0e652e6ed741acf5a68cec347c71fa5d26e4e1f/nix/docker.nix#L89)

**Comment by atomlab** [comment]
I understand yours point. I shouldn't use env variable `NETWORK=mainet` for `cardano-submit-api`.

Doesn't work as expected
```
docker run -e NETWORK=mainnet inputoutput/cardano-submit-api:<TAG> --listen-address 0.0.0.0
```
Works!
```
docker run -v $PWD/config.yaml:/config.yaml inputoutput/cardano-submit-api:<TAG> \
--config /config.yaml --mainnet --socket-path /node-ipc/node.socket --listen-address 0.0.0.0
```

**Comment by ksemaev** [comment]
@rhyslbw this setup is very limitted, since mapping configs, passing args etc is fine for sandbox envs, docker or docker-compose runs. With global tools like kubernetes etc it's considered to use variables as the easiest way to pass config options.

Currently I do have to rebuild your image just to change the start script with (and I had to do docker inspect to grab this constantly changing randonly named files and paths):
```ENTRYPOINT ["/nix/store/7dn6h4ix2y1jc2gg5219mrwgny5fjkjy-cardano-submit-api-exe-cardano-submit-api-2.1.1/bin/cardano-submit-api", \
            "--socket-path", "/node-ipc/node.socket", \
            "--mainnet", \
            "--listen-address", "*", \
            "--config", "/nix/store/fhyvl8jxymk2nrivyv77y1sp432vgz44-submit-api.json" \
            ]
```

So even if I want to use the approach shown here and pass args, I still would need to build an image to pass config.yaml. But I'm happy with default config, all I want is to change listen-address, but to do that I have to pass all_the_other_args and map a config file. This is really not very convinient, can you consider moving those config options to envs in next release?

**Comment by rhyslbw** [comment]
@ksemaev the Docker experience will be improved here. You will be able to effortlessly interact with the entrypoint, and therefore simply configure using service command, even in Kubernetes. Have a look at https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/ and stay tuned for updates
