### ISSUE TITLE
Explorer API - request for slot over 65535 returns out of bounds error

### ISSUE THREAD

**Issue by melmccann** [input-output-hk/cardano-rest#79]
The following request:
`curl http://127.0.0.1:8100/api/epochs/208/206060`
Returns the following error: 
`out of bounds: `206060' (should be between 0 and 65535)`

**Comment by ArturWieczorek** [comment]
Fixed: 

`curl http://127.0.0.1:8100/api/epochs/208/206060`

```json
{
   "Right":[
      {
         "cbeEpoch":208,
         "cbeSlot":206060,
         "cbeBlkHeight":4500791,
         "cbeBlkHash":"0cd7a140c24b1e371deb2b142996b65a6316fe3ed5150e3caade841be5b285b2",
         "cbeTimeIssued":1596265151,
         "cbeTxNum":2,
         "cbeTotalSent":{
            "getCoin":"207103134025"
         },
         "cbeSize":800,
         "cbeBlockLead":"f14f712dc600d793052d4842d50cefa4e65884ea6cf83707079eb8ce302efc85",
         "cbeFees":{
            "getCoin":"362594"
         }
      }
   ]
}
```
New explorer for 208/206060 :

https://explorer.cardano.org/en/epoch.html?number=208&page=1029&perPage=10
https://explorer.cardano.org/en/block?id=0cd7a140c24b1e371deb2b142996b65a6316fe3ed5150e3caade841be5b285b2
