### ISSUE TITLE
Dbsync fix for lovelace field broke REST API

### ISSUE THREAD

**Issue by astudnev** [input-output-hk/cardano-rest#96]
Master build does not work with the latest fix from db-sync:
https://github.com/input-output-hk/cardano-db-sync/pull/352

which is the ONLY option i found to index the current chain mainnet.

Running REST with this database respond with error:
```
Oct 19 15:56:34 node1-3 result[28084]: PersistMarshalError "Failed to parse Haskell type `Word64`; expected integer from database, but received: PersistRational (50229086023 % 1). Potential solution: Check that your database schema matches your Persistent model definitions."
```

**Comment by KtorZ** [comment]
Fixed by https://github.com/input-output-hk/cardano-rest/releases/tag/3.0.0
